### ISSUE TITLE
loadData breaks

### ISSUE THREAD

**Issue by bborn** [e1himself/sir-trevor-columns-block#2]
Just trying to implement this in my CMS, and loadData seems to break here: https://github.com/e1himself/sir-trevor-columns-block/blob/master/src/columns-block.js#L178

Looks like that line needs to be this instead:

```
$block = this.editorInstance.block_manager.createBlock(block.type, block.data, $block ? $block.$el : $column.children('.st-block-controls__top'));
```

(Maybe they moved `createBlock` off of the `editorInstance` and into the `block_manager` in a recent commit?)

**Comment by bborn** [comment]
Weird. I see now that my file was corrupted or something (or maybe I accidentally deleted a bit out of that line). Works fine.

**Comment by e1himself** [comment]
Great! :)
