### ISSUE TITLE
AMD module

### ISSUE THREAD

**Issue by bborn** [e1himself/sir-trevor-columns-block#3]
Any chance you could make this AMD compliant? I'm trying to load it using requirejs, and having to use a shim for this lib. I'm not sure the best way to do it (I'm a little out of my range of experience here), but maybe something like:

```
define(['sir-trevor-js'], function(SirTrevor){
    SirTrevor.Blocks.Columns = SirTrevor.Block.extend({
       .... etc ....
    })
})
```

**Comment by e1himself** [comment]
Hi! 

I've added AMD support. Please see [example/index.amd.html](https://github.com/e1himself/sir-trevor-columns- block/blob/master/example/index.amd.html) for installation demo.
