### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by SgtOddball** [e1himself/sir-trevor-columns-block#6]
I've been having a play with the columns block (Some very nice work I must say) but I've noticed a problem with the sir-trevor-icons file - namely from what I can tell it's still looking for the old style 'twocolumns' content attr rather than the updated 'columns-6-6'.

I've had a look at the woff file and from what I can tell the changes are there but for the life of me I can't get it to render the icons without reverting to 'twocolumns' etc.

**Comment by e1himself** [comment]
Hi Chris!

Looks like we need to recompile either fonts or css with inlined fonts.
I'll check that tomorrow!

**Comment by e1himself** [comment]
@SgtOddball 
Currently I cannot reproduce the issue. Everything seems to be ok.

Can give me more details on this?
- Do you use latest master version or version installed via bower?
- What browser do you use? Can you tell which font file is loaded (we have _eot_, _svg_, _ttf_ and _woff_). You can check this using "Network" panel in Chrome development tools.

Thanks.

**Comment by e1himself** [comment]
@SgtOddball 

I've found that `bower install e1himself/sir-trevor-columns-block` installed v0.1.1 which does not contain latest fixes from master. It's likely that you used that version.

So I've created a new release v0.1.2. 
Please check if your icons issue is still reproduced with the new release.

**Comment by SgtOddball** [comment]
I must confess I don't use bower at the moment since we use .net (probably move over to using it once vs 2015 is out proper). 

But I've rejigged it and it's working fine now. Thanks for the help!

**Comment by e1himself** [comment]
@SgtOddball 

I've rolled out a new release that has all scripts already built and ready to use. 
Also it has a single css file (which should be easier to install into your project).

Check v0.3.0

Best regards!

**Comment by SgtOddball** [comment]
Cool, I'll get them added (was having some weird issues with the columns at the moment anyways so fingers crossed this might solve them).
