### ISSUE TITLE
Editor store not being updated

### ISSUE THREAD

**Issue by SgtOddball** [e1himself/sir-trevor-columns-block#7]
I've been scratching my head over this one but It appears that  the columns block isn't updating the editor store value in the text area on the form submission (either by form submission event or just ye olde submit button).

The only thing present in the store is the defaults used when initialising the sir trev instance (And yes, I'm using the latest instance of the 'Mr Trevor' fork which still works perfectly fine when not calling the columns block). 

On a side note, I've had a look through the core mr trev vs sir trev and the only real difference I can find at the moment is lines 10537 - 10539; 

``` javascript
getTextBlockHTML: function() {
    return this._scribe.getHTML();
},
```

vs

``` javascript
getTextBlockHTML: function() {
    return this._scribe.getContent();
},
```

Everything else seems to relate to the format bar (which I've updated updated/rolled back but to no effect other than making the format bar wander off if you have to scroll).

**Comment by e1himself** [comment]
Hi Chris!

Yeah, you're right! It looks like Sir Trevor has changed it's Blocks API, so we need to call another method to store content. I'll fix it tomorrow.

Thanks!

**Comment by SgtOddball** [comment]
_Phew_ thought I was going mad and/or buggered it over. The odd thing is I'm using another block that's behaving itself just fine, had a look over things but couldn't see what I was missing. 

If you can let me know how you get on I'd be grateful.

**Comment by e1himself** [comment]
Chris,

I've tested the latest plugin release with latest Mr. Trevor installed via bower and have found nothing wrong with it. It updates textarea on form submit as it should do.

Here's an example installation: http://demo.e1stuff.com/sir-trevor/.
It outputs textarea content on form submit.

``` js
$('form').bind('submit', function () {
    $('#st-json-debug').text($('.sir-trevor').val());
    return false;
});
```

And as far as I see it works.

Can you provide example on which I can reproduce the issue? Or am I missing something?

**Comment by SgtOddball** [comment]
I think I see the problem (got Bower going yesterday but hadn't got round to compairing files with the ones in my project yet), The originals I had (dated 2015-03-12) are not the same as the ones that bower provided (dated 2015-03-13) plus quite a few lines of code different, and that was just on the 'mr-trevor' file. So I'll update with the bower files and let you know how I get on.

**Comment by SgtOddball** [comment]
In a really frustrating turn of things it's still spitting out;

``` json
{"data":[{"type":"columns","data":{"columns":[{"width":6,"blocks":[]},{"width":6,"blocks":[]}],"preset":"columns-6-6"}}]}
```

No matter what gets changed. I'm going to take it back to a basic page without the rest of the files I've got going on (It's been added to a bootstrap framework) and see if I can figure out what's disturbing it if I start from the group up.

**Comment by e1himself** [comment]
- Does the demo working ok for you?
- How your SirTrevor is initialized? Maybe it's because of some extra options?

**Comment by SgtOddball** [comment]
The demo's working fine, I've got it working at my end on a blank template (sod's law) and I'm just in the process of rebuilding the page it's been failing on... So far it's working fine so once I know it's working right I'll compare with the original and let you know what I find.

**Comment by e1himself** [comment]
Great!
Good luck! :)

**Comment by SgtOddball** [comment]
So good so far, still getting format wandering off (easy to replicate, just add enough blocks/text to require scrolling and there you go).

From what I can see it was being sensitive to being opened after another custom block. That's pretty much the only thing I can find that's triggering it. 

So pretty much a case of calling the blocks js file directly after the Mr Trevor file is called. 
What's bizarre is I did think that might be the case and stripped it out while testing but to no avail. 

Anyways, I'm closing this since it's working. Thanks for your help though.
