### ISSUE TITLE
Why is this abandoned? 

### ISSUE THREAD

**Issue by cosmomathieu** [e1himself/sir-trevor-columns-block#8]
Has this feature been included in Sir Trevor js?

**Comment by SgtOddball** [comment]
Nope, they covered why in detail under a few issue topics on Sir Trevor.

As to why the column block project has been stopped, it's a case of the main project has moved on and it would take alot of work to update over from the beta version of Sir Trev v0.5 to the current v0.6 release. 

On that same note though at some point I do mean to see if I can figure out what's involved and create another branch but at the moment I don't have the time to spare to take this up.

**Comment by cosmomathieu** [comment]
Thanks for the reply. I would like to jump on the dev of this feature, but am still quite new to jQuery. If I were to pick up development of this branch to make it current, would you be available to review my commits every now and then? In your experience, can the multi column block be built as a plugin, or extension to SirTrevorJs as oppose to hacking the core?

**Comment by SgtOddball** [comment]
Welp, with regards to Sir Trevor v0.6 they've moved away from jQuery anyway so that would be a moot point. 

As to picking up development, I'm not in a position to really get into the nuts and bolts of it as I'm quite time poor outside of work so the bits and pieces I work on are when I've got some free time and so very sporadically. 

As to the changes done to the core, I think they were still needed but they're not major re-writes so it might be that involving.

**Comment by e1himself** [comment]
For the history: here's the pull request mentioned by @SgtOddball:
https://github.com/madebymany/sir-trevor-js/pull/297

I'm closing the issue.

**Comment by SgtOddball** [comment]
It might be worth looking over matters again once the dust has settled on v0.6 but there's still ongoing changes (especially with regards to the UX of the whole kitten-caboodle) but I've got some ideas on how to add the columns has a plugin without changes to the core (risky I know and possibly recursive in places but I've got some ideas that I might pad out whilst I'm waiting for my current role to wind up). 

So watch this space but don't hold your breath... (and many other idioms of that nature).

**Comment by e1himself** [comment]
I think [draft.js](https://facebook.github.io/draft-js/) is the way to go.
I'd better invest time in it.

**Comment by cosmomathieu** [comment]
Never heard of draft.js until today. Looked into it and realized now I need to learn React.js lol. This is a good thread to keep up with. Thanks guys.
